---
title: "Enhancing Ceramic Petrography Through Deep Learning"
author: 
  - name: Ashley Rutkoski
    affiliation:
      - ref: flmnh
  - name: Nicolas Gauthier
    email: nicolas.gauthier@ufl.edu
    affiliations:
      - ref: flmnh
    attributes:
      corresponding: true
  - name: Neill Wallis
    affiliations:
      - ref: flmnh
  - name: Andrea Torvinen
    affiliations:
      - ref: flmnh
  - name: Ann Cordell
    affiliation:
       - ref: flmnh
affiliations:
  - id: flmnh
    name: University of Florida
    department: Florida Museum of Natural History
    address: 1659 Museum Road
    city: Gainesville
    state: FL
    postal-code: 32611-7800
abstract: |
  Clay recipes reveal information about the local geology and the inclusion of different additives that make up a vessel, which in turn reflects the social, environmental, and technological context of ceramic manufacture. Ceramic petrography has long been instrumental in shedding light on key manufacturing techniques, identifying unique mineralogical signatures, and assessing patterns of cultural exchange among diverse communities. However, traditional methods used to characterize and quantify petrographic thin sections can be labor intensive and time consuming, making it difficult to meet the increasing demand for large comparative datasets. Here, we present recently developed machine-learning algorithms to enhance the efficiency, accuracy, and accessibility of these intricate analyses. We review the basics steps for conducting these approaches and illustrate its practical application for being incorporated into a petrographer’s standard toolkit. Streamlining petrographic workflows through machine-learning techniques will open new avenues for the quantitative and qualitative assessment of ceramic technology and its broader implications for past societies.
keywords: 
  - computer vision
  - thin sections
  - image analysis
date: last-modified
bibliography: bibliography.bib
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal of Archaeological Science
      formatting: preprint
      model: 3p
      cite-style: authoryear
editor: visual
---

## Introduction

[this section should convey the use and importance of ceramic petrography in archaeology and why it has within remained valuable even with the advent of new technology and compositional methods]{style="color:red;"}

The use of compositional studies like INAA, XRD, and Petrography in archaeology today seems rather common place, as it is routinely employed to identify and quantify the mineralogical make up of ceramic artifacts. Since the early 1930s, the application of thin-section petrography in archaeology has been extremely valuable in providing a glimpse into the ceramic production process and information about the broader communities in which it was formed. The dynamic environment, that formed the clay and various additives used global to temper ceramics, and the complex pottery traditions that existed in the past ultimately influenced quantity and types of inclusion documented in the clay recipes.

[what can we learn from ceramic petrography and how does it differ and surpass the new technological methods i.e., is it cheaper? why has it remained important and in use]{style="color:red;"}

Compositional studies, generally broken down into two approaches mineralogical (e.g., petrography, XRD, etc.) or geochemical (e.g., INAA, ), have been the key to identifying the inclusions and voids that provide information about the past communities that archaeologists are trying to study by identifying variability in recipes and unique geological features that can connect manufacturing locations and the social network in which vessels operate within.

the use of this "traditional" method i.e., thin section petrography has continued to persist even with the rise of technology and increased accessibility of other elemental compositional methods.

[despite these advantages what are the current issues facing petrography..... standardization, smaller sample sizes give the time commitment, etc. ask Andrea about this eventually after researching]{style="color:red;"}

[the development of AI and how it can be used in different disciplines]{style="color:red;"}

## Methods

[@lyons2021]

[@rubo2019]

[@aprile2014]

[@lopez2015]

### Petrographic thin sections

### Image acquisition

### Deep learning

#### Image classification

#### Semantic segmentation

[@wu2019detectron]

#### Instance segmentation

#### Panoptic segmentation

## Results

#### Image classification

#### Semantic segmentation

#### Instance segmentation

#### Panoptic segmentation

## Discussion

### Future work

## References
